---
deployment:
  tasks:
    - export DEPLOYPATH=/home/hieront4/leo_ns/
    - /bin/cp -R . $DEPLOYPATH
    - cd $DEPLOYPATH && npm install
    - cd $DEPLOYPATH && npm run build
    - cd $DEPLOYPATH && npm prune --production